### PR TITLE
Studyscreens

### PR DESCRIPTION
**Pull request by karkar**
Updated current trial page to reflect ongoing trial
Added page for logging breakfast compliance (needs to be routed)

Current study entries to be divided into:
- before breakfast: just shows the condition for the day
- during breakfast: prompts for compliance with condition and
additional images if need
- after breakfast: prompts for nothing eaten post b-fast compliance and
symptom severity level

Removed ten-padding css class since there was a default ionic class
which provided same padding.

Added a divcenter class for centering buttons

----

Added post page
Removed jsocontroller folder (no idea how it was created)

Will need to add JQuery + JQuery UI for the symptom scale slider.

----

Installed ngCordova & camera plugin
$ bower install ngCordova --save
$ cordova plugin add org.apache.cordova.camera

Added separate controller for all ngCordova controllers (currently,
only camera)

### CODE REVIEW

**Comment by jayfo** [comment]
Why you need JQuery UI?

I'm hesitant to start mixing a bunch of said libraries?

**Comment by karkar** [comment]
Yeah, I want to avoid jquery if possible too. Since we're already throwing d3 in the mix as well.

I was searching for a slider in angular ui and it is basically rehashing jquery slider https://github.com/angular-ui/ui-slider This is for the symptom level response.

**Comment by karkar** [comment]
There are non-jquery options but those are 3rd party libs written on top of angular ui. 
eg: http://prajwalkman.github.io/angular-slider/

**Comment by jayfo** [comment]
What UI effect are you trying to achieve, such that the Ionic sliders don't
work?

**Comment by karkar** [comment]
Ionic does not have sliders from what I saw. 
http://ionicframework.com/docs/api/

They have sliders for pages and menus, not for input.

**Comment by jeffsco** [comment]
> 
> Ionic does not have sliders from what I saw. 
> http://ionicframework.com/docs/api/
> 
> They have sliders for pages and menus, not for input.

They have slider looking things called Range (under CSS).

J

**Comment by karkar** [comment]
:facepalm: Thanks Jeff. We can send this thread to the grave now.

**Comment by jayfo** [comment]
Issue close.  ;)

**Comment by karkar** [comment]
Technically not an issue :P

**Pull request merged**
